### ISSUE TITLE
Error: Not implemented

### ISSUE THREAD

**Issue by Grotex** [JuliaDynamics/RigorousInvariantMeasures.jl#112]
I find an error in [RigorousInvariantMeasures.jl](https://github.com/JuliaDynamics/RigorousInvariantMeasures.jl):
run this in Julia
```
> using InvariantMeasures

> using ValidatedNumerics

> using Plots

> using LaTeXStrings

> using StatsPlots

> D0 = PwMap([x->4*x*(1-x),
            x->2*x,
            x->2*x-1],
           [@interval(0), @interval(3/8), @interval(1/2), @interval(1)])

> D = D0 ∘ D0# an iterate

> B = Ulam(1024)

> Q = DiscretizedOperator(B, D, 0.0)

```

An error up:

> ┌ Error: Not implemented
> └ @ InvariantMeasures.DynamicDefinition C:\Users\Administrator\.julia\packages\InvariantMeasures\loihW\src\DynamicDefinition.jl:15
> MethodError: no method matching +(::Nothing, ::Int64)
> Closest candidates are:
>   +(::Any, ::Any, ::Any, ::Any...) at E:\Julia-1.7.3\share\julia\base\operators.jl:655
>   +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at E:\Julia-1.7.3\share\julia\base\int.jl:87
>   +(::MultivariatePolynomials.RationalPoly, ::Any) at C:\Users\Administrator\.julia\packages\MultivariatePolynomials\0oEYT\src\rational.jl:50
>   ...
> 
> Stacktrace:
>  [1] iterate(S::InvariantMeasures.BasisDefinition.DualComposedWithDynamic{Ulam{LinRange{Float64, Int64}}, InvariantMeasures.ComposedDynamic}, state::Tuple{Int64, Int64, Nothing})
>    @ InvariantMeasures C:\Users\Administrator\.julia\packages\InvariantMeasures\loihW\src\UlamBasis.jl:31
>  [2] iterate(S::InvariantMeasures.BasisDefinition.DualComposedWithDynamic{Ulam{LinRange{Float64, Int64}}, InvariantMeasures.ComposedDynamic})
>    @ InvariantMeasures C:\Users\Administrator\.julia\packages\InvariantMeasures\loihW\src\UlamBasis.jl:29
>  [3] assemble(B::Ulam{LinRange{Float64, Int64}}, D::InvariantMeasures.ComposedDynamic, ϵ::Float64; T::Type)
>    @ InvariantMeasures C:\Users\Administrator\.julia\packages\InvariantMeasures\loihW\src\GenericAssembler.jl:21
>  [4] DiscretizedOperator(B::Ulam{LinRange{Float64, Int64}}, D::InvariantMeasures.ComposedDynamic, ϵ::Float64; T::Type)
>    @ InvariantMeasures C:\Users\Administrator\.julia\packages\InvariantMeasures\loihW\src\GenericAssembler.jl:60
>  [5] DiscretizedOperator(B::Ulam{LinRange{Float64, Int64}}, D::InvariantMeasures.ComposedDynamic, ϵ::Float64)
>    @ InvariantMeasures C:\Users\Administrator\.julia\packages\InvariantMeasures\loihW\src\GenericAssembler.jl:60
>  [6] top-level scope
>    @ In[20]:1
>  [7] eval
>    @ .\boot.jl:373 [inlined]
>  [8] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
>    @ Base .\loading.jl:1196

How to debug this error?

**Comment by orkolorko** [comment]
Hi @Grotex , sorry it took me some time to answer.
The computation of the matrix works on my computer, which seems to fail on yours.
Can you try to run only:
```
using RigorousInvariantMeasures, IntervalArithmetic
D0 = PwMap([x->4*x*(1-x),
            x->2*x,
            x->2*x-1],
           [@interval(0), @interval(3/8), @interval(1/2), @interval(1)])
D = D0 ∘ D0 ∘ D0 # it needs some more expansion to prove a Lasota-Yorke automatically
B = Ulam(1024)
Q = DiscretizedOperator(B, D, 0.0)
```
without loading other packages?

There is some issue in proving automatically the Lasota-Yorke I'm looking into, but the matrix assembly is working fine.
Can you tell me your system?

**Comment by fph** [comment]
Can I also ask which version of the package you are running? Your Julia complains about an error in `\src\UlamBasis.jl:31`, but that line contains only comments (since last October's commits at least). I would suggest you to update the package first and see if the error is still there. :)

**Comment by Grotex** [comment]
> Can you tell me your system?

I use Win10.

> Can you try to run only:

```
using RigorousInvariantMeasures, IntervalArithmetic
D0 = PwMap([x->4*x*(1-x),
            x->2*x,
            x->2*x-1],
           [@interval(0), @interval(3/8), @interval(1/2), @interval(1)])
D = D0 ∘ D0 ∘ D0 # it needs some more expansion to prove a Lasota-Yorke automatically
B = Ulam(1024)
Q = DiscretizedOperator(B, D, 0.0)
```

> without loading other packages?

Uhmmm...I use 'InvariantMeasures' in Pkg instead. It would be the true cause.

**Comment by Grotex** [comment]
> Can I also ask which version of the package you are running? Your Julia complains about an error in `\src\UlamBasis.jl:31`, but that line contains only comments (since last October's commits at least). I would suggest you to update the package first and see if the error is still there. :)

OK

**Comment by Grotex** [comment]
Thank you @orkolorko @fph 
After updating the package the error disappears

**Comment by fph** [comment]
OK, I'm glad it went away! Just for your curiosity: from the look of it, it seems it was caused by an argument being `nothing` in a call to `iterate` for `UlamBasis`; that argument is the result of a call to `preimage`, so the real reason is `preimage` failing to compute a preimage. Your function is not full branch, so that may be the cause (though the package should work also in that case, and indeed I am glad the fixes helped).
