### ISSUE TITLE
Performance regression on Lorenz

### ISSUE THREAD

**Issue by fph** [JuliaDynamics/RigorousInvariantMeasures.jl#140]
After merging the new `root` code, I have re-run the large-scale Lorenz experiment and I noticed a major regression in terms of CPU time:
```julia
[ Info: Size coarse: 131072 Size fine: 16777216
[ Info: (0.920710061951757, 48.430648632351506)
[ Info: The fine error is 0.008614304440211202
[ Info: The density is bounded above by 610.8044705859709
[ Info: Computed [0.651548, 0.715594], with precision 0.06404495238474539
481492.331611 seconds (1.49 T allocations: 68.712 TiB, 1.59% gc time, 0.01% compilation time)
```

This was with the method that computed the preimages of the two endpoints of each interval, in January:
```julia
[ Info: Size coarse: 131072 Size fine: 16777216
[ Info: (0.9207100619517596, 48.430648632351506)
[ Info: The fine error is 0.008614198013449238
[ Info: The density is bounded above by 610.8044705859915
[ Info: Computed [0.651549, 0.715594], with precision 0.06404416812589586
174033.739884 seconds (554.73 G allocations: 28.801 TiB, 2.01% gc time, 0.00% compilation time)
```

And this was with the old method based on interval Newton alone (which had trouble with zero derivatives), and before I fixed the bug with `dfly_inf_der`.
```julia
julia> @time include("compute_lyapunov_Lorenz_test.jl")
[ Info: Size coarse: 131072 Size fine: 16777216
[ Info: (0.9063632667125474, 176.35568356074037)
[ Info: The fine error is 0.02768949263728258
[ Info: The density is bounded above by 1883.4027776188152
[ Info: Computed [0.580676, 0.786467], with precision 0.20578955707451752
101827.678510 seconds (293.23 G allocations: 17.633 TiB, 1.99% gc time, 0.01% compilation time)
```
This version has worse dfly constants that lead to worse estimates, but nevertheless the assembly time should be similar, and instead it has increased 4.8x.

We need to re-think that; I suspect the bisection step at the beginning of the loop in `root` and things like that do more harm than good.

**Comment by orkolorko** [comment]
I was thinking the following: and if during the constructor phase of the dynamic we add a range_estimate step for the derivative which to each branch assigns a flag so that a different root method can be called if the computer proves that the derivative range does not contain 0?
This would allow to use a faster method in most cases, and the two roots or bisection method are going to be called only if strictly necessary.

**Comment by fph** [comment]
I think we can (and should) try to handle everything with a single method. 

* I suspect the main culprit is the attempt to try bisection first and then Newton. We want most of the work to be Newton iterations, not bisection, in the typical case. And it's better to do them in the opposite order, since a failed Newton step already computes the quantity `f(mid(x))` that we need to apply bisection.
* @orkolorko Would you be opposed to me trying to implement something very similar to the [approach](https://github.com/JuliaDynamics/RigorousInvariantMeasures.jl/blob/BetterContractors/src/Contractors.jl#L70) in the branch that we had discarded? TL;DR: we try first Newton (or Krawczyk if 0 \in f'(mid(x))), then if it fails we try with bisection, then if it fails, too, we try chopping off a smaller section of the interval from the endpoints.
* If you think that the final factor 2 is too loose, we can refine the strategy to further to reduce it, testing points that have a distance from the endpoints equal to 1/8, 1/16, ... of `diam(x)`. I suspect this case happens very rarely, since `0 \in f(Interval(mid(x)))` is very unusual in the first place.
* It is not 100% clear to me if the strategy of computing the two preimages `preim(y.lo)` and `preim(y.hi)` separately gives tighter intervals, but I suspect it might, especially in cases when the intervals get larger, so I would suggest to keep it even if it slows the computation down a little. It shouldn't be that bad.
* The main mathematical difficulty is branches defined on `br.X = (a, b)` where `a` and `b` are not thin. But I think that we can solve this issue by handling explicitly the cases where `preim(y.lo)` and `preim(y.hi)` overlap with `a` and `b`: if one of them overlaps with `a`, then it should be enlarged to contain the whole `a`, and the same with `b`.

**Comment by fph** [comment]
> * The main mathematical difficulty is branches defined on `br.X = (a, b)` where `a` and `b` are not thin. But I think that we can solve this issue by handling explicitly the cases where `preim(y.lo)` and `preim(y.hi)` overlap with `a` and `b`: if one of them overlaps with `a`, then it should be enlarged to contain the whole `a`, and the same with `b`.

Hmm no, in retrospect this seems trickier than I imagined when I wrote this, because I would like to rely on monotonicity inside `root`, too, so that we can use `f(mid(x))` to discard one interval instead of using `bisect(x)` which produces worse enclosures. I'll think about it but your solution of checking `f(a)` and `f(b)` explicitly may already be the best choice.

**Comment by orkolorko** [comment]
Yes, I think you can go ahead.
About testing for monotonicity, I thought about that and we need to evaluate the derivative only on ` br.X[1]`  and `br.X[2]`
because the branch is monotonic on the rest of the interval by default.

Therefore adding the flag monotone or nonmonotone at the construction step would be almost free...

**Comment by fph** [comment]
Actually, now that I think about it, I think we do not need to do anything special to treat the cases that are non-monotonic at the edges. Currently we are assuming that branches are monotonic as we create them; then the information we have is:

* a strictly monotonic function $f: [x_1, x_2] \to \mathbb{R}$,
* enclosures $\mathbf{x}_1 \ni x_1$, $\mathbf{x}_2 \ni x_2$,
* enclosures $f(x_1) \in \mathbf{y}_1 \subseteq f(\mathbf{x}_1)$ and $f(x_2) \in \mathbf{y}_2 \subseteq f(\mathbf{x}_2)$ (sometimes the `MonotonicBranch` struct contains better enclosures, for instance we may know that $f(x_1)=0$ exactly).
* an $y$ (possibly an interval, but usually we'll want to apply this to `y.lo` and `y.hi`), for which we are looking for the (unique) preimage $x = f^{-1}(y) \in [x_1, x_2]$. We can assume that $y \in hull(\mathbf{y}_1,\mathbf{y}_2)$; the fact that there may be no preimage is handled already inside `preimages` (plural) using `{first,last}_overlapping`.

The function $f$ can be non-monotonic on $[\mathbf{x}_1.lo, x_1]$ and $[x_2, \mathbf{x}_2.hi]$, and this is the tricky case. A practical example is: $\mathbf{x}_1 = [prevfloat(\sqrt{2}), nextfloat(\sqrt{2})]$, $\mathbf{x}_2= 2$, and $f(x) = (x-\sqrt{2})^2$.

Typically we pass $\mathbf{x} = hull(\mathbf{x}_1, \mathbf{x}_2)$ to `root()` as a search domain, so the exact value of $\mathbf{x}_1.hi$ and $\mathbf{x}_2.lo$ is lost.

In any case the following result (and the analogous one for the other end of the interval) holds and can be used to restrict the search interval when the first-order methods interval Newton/Krawczyk fail: 

**Theorem**: let $z\in\mathbb{R}$ (a point, not an interval). if $y \not\in hull(\mathbf{y}_1, f(z))$, then $x \in hull(z, \mathbf{x}_2)$, and hence we can take $z$ as a new left endpoint of the search interval.
**Proof**: if $z \geq x_1$, then we are in the monotonic part of the function and by monotonicity $x > z$. If $z < x_1$, then the statement is trivially true because we already know that $x \in [x_1, x_2]$.

Do you agree with this theorem? Or am I making some mistakes? If so, then the strategy I was using in the initial branch works even in the tricky case and we can use that directly.

**Comment by orkolorko** [comment]
I think the theorem is true, let's try this other approach.

**Comment by fph** [comment]
I have implemented the new preimage strategy, which mitigates the issue on Lorenz:
```julia
[ Info: Precompiling RigorousInvariantMeasures [6103b61f-200f-420b-b397-2cbeef157920]
[ Info: Size coarse: 131072 Size fine: 16777216
┌ Info: Assembling operator, the Newton stopping options are
└                       ϵ = 1.0000000000000008e-14, max_iter = 100
[ Info: (0.9207100619562983, 48.430648634093586)
[ Info: The fine error is 0.008615364985530321
[ Info: The density is bounded above by 610.804470642926
[ Info: integral small interval [2.3172e-07, 2.31721e-07]
[ Info: BoundObs [3.68449, 3.6845]
[ Info: notLinf 0.03202638285946186
[ Info: lyap [0.651544, 0.715598]
[ Info: Computed [0.651544, 0.715598], with precision 0.06405276754302558
118503.109909 seconds (349.92 G allocations: 20.036 TiB, 1.61% gc time, 0.03% compilation time)
```
I still want to check the performance on the BZMap before merging branch `BetterContractors2`, but it is almost ready.
