### ISSUE TITLE
Wrong derivatives for decreasing maps

### ISSUE THREAD

**Issue by fph** [JuliaDynamics/RigorousInvariantMeasures.jl#153]
I am afraid we have a bug when using `preimages_with_derivatives` with compositions of decreasing maps.
```julia
julia> D0 = PwMap([x->1-x^2], [0..0,1..1])
Piecewise-defined dynamic with 1 branches

julia> D = D0 ∘ D0
RigorousInvariantMeasures.ComposedDynamic((Piecewise-defined dynamic with 1 branches, Piecewise-defined dynamic with 1 branches), Piecewise-defined dynamic with 1 branches)

julia> x, xl, xp = RigorousInvariantMeasures.preimages_and_derivatives([0..0, 0.5..0.5, 1..1], D; ϵ=1e-14, max_iter=100)
(Interval{Float64}[[0, 0], [0.541196, 0.541197]], [1, 2], Interval{Float64}[[0, 0], [0, 0]])
```
The second element of `xp` is the derivative of $1 - (1-x^2)^2$ in $1-1/\sqrt{2} \approx 0.541196$, which should be $5\sqrt{2} - 6 \approx 1.07$, not 0. The problem is that our approach is focused on identifying preimages of intervals, while `preimages_and_derivatives` cares about identifying preimages of points. To map one to the other we "tag" with each interval the preimage of its leftmost point, but decreasing maps reverse the endpoints, so the image of the interval `[a..b]` is the interval `[f(b)..f(a)]` in the reverse order.

Some more work is needed to make `preimages_and_derivatives`, and in general the concept of preimages, more robust.

This only affects computation with `Hat` and maps with decreasing branches; in particular, none of the examples in our paper is affected (luckily)!

**Comment by orkolorko** [comment]
One of the reasons why I was thinking in breaking up the computation of the operator in each branch is that 
I think that going from `preimages(br)` to `preimages(D)` loses information on the branch orientation.
I do not know if this is connected with the issue; I will try to look into this issue in the next days, also.

**Comment by fph** [comment]
Precisely, it is related to branch orientation. 

Brief analysis: suppose we have a composed dynamic $f\circ g$. We want to compute each point $x_{i,j,k} = g_i^{-1}f_j^{-1}(z_k)$ of the partition $[z_1, z_2, ... z_K]$, over all branches $f_j$ of $f$ and all branches $g_i$ of $g$. Suppose for simplicity that each map is full-branch, so all these preimages exist.

There are major savings w.r.t. treating it as a PwMap separately, though: one can start by computing the preimage $y_{jk}=f_j^{-1}(z_k)$ for each $j$ and $k$, and then from each of these preimages compute $x_{ijk} = g_i^{-1}(y_{jk})$ for each $i$. So in practice you can run `y = preimages(z, f)` and then `x = preimages(y, g)`. An entirely branch-based approach would instead compute the preimages $(f_i \circ g_j)^{-1}(z_k)$ for all $i,j,k$, and lead to a duplication of efforts since you recompute the same quantity $y_{jk}$ each time for $i$ times. The "shooting method" that we used previously had this drawback, indeed.

These savings carry over to the derivatives:
$$(f\circ g)'(x_{ijk}) = f_j'(y_{jk}) g_i'(x_{ijk}).$$
The first factor depends only on the first preimage, and we do not want to recompute it for each $i$; so in practice to make this computation we run `y, ylabel, dy = preimages_with_derivatives(z, f)` and then the vector of derivatives `dy` contains the factors $f_j'(y_{jk})$ that we need, and `ylabel` contains the information about which derivative is which.

The tricky detail is that in our implementation we do not use the pair $(j,k)$ as an index of $y$, but we just list all the valid $y_{\ell}$ one after the other to create a partition; this is more efficient for non-full-branch maps, since for some pairs $(j,k)$ a valid preimage does not exist. The information about $(j,k)$ is saved indirectly in `ylabel`: `ylabel[\ell]` tells you the index $k$ such that the preimage of $[y_\ell, y_{\ell+1}]$ is $[z_k, z_{k+1}]$. This is very handy for the Ulam assembler, since it is exactly the information that you need to compute it. Indeed the interface was devised thinking about it first.

However, this information is orientation-dependent: if the branch is increasing then it means that $f_j(y_\ell)=z_k, f_j(y_{\ell+1}) = z_{k+1}$, while if the branch is decreasing this means that $f_j(y_\ell)=z_{k+1}, f_j(y_{\ell+1}) = z_{k}$.

In the current implementation the line `derivatives[zindex]` essentially always takes $dy_\ell$ as the first factor $f_j'(y_{jk})$; but if the branch is decreasing this is the wrong endpoint.

There is a further subtle detail related to which preimages we compute: at the moment we want to make sure that the computed vector `y` defines is a partition of dom(f); so we obtain it by taking for each branch `f.branches[i]` a vector that always starts with the left endpoint $a$ of $[a,b] = dom(f_i) =$`f.branches[i].X` (and, for non-full-branch maps, this is not the preimage of any point in the partition `z`), and ends with an "implied" $b$, which is not written explicitly in the vector. In this way it is sufficient to concatenate all vectors relative to each branch, in order of appearance, to compute a preimage relative to the whole dynamic. So, in particular, the vector `dy` contains the derivative $f_j'(a)$ but not $f_j'(b)$, and this is a problem when composing decreasing branches, because we need the latter and not the former.

So, conclusions:
* we need to re-think what we output in `preimages` and `preimages_and_derivatives`. `Ulam` cares about intervals, and `Hat` cares about derivatives in single points of the preimages, and we need a way to reconcile the two.
* in the case of composed maps, unfortunately computing things separately for each branch of $f\circ g$ is not the solution because it leads to a lot of duplication.

**Comment by fph** [comment]
And it is not even clear a priori which derivatives we need to compute; for instance if the partition is `z = [0; 0.5; 1]`,  if we want to compose f with an increasing branch of g we need $f'(f^{-1}(0))$ and $f'(f^{-1}(0.5))$, if we want to compose it with a decreasing branch of g we need $f'(f^{-1}(0.5))$ and $f'(f^{-1}(1))$, if I am not mistaken.

And if g has both increasing and decreasing branches, we need all three, `y` and `dy` should not have the same size. (Actually this should not happen if we assume to be in the special case that we need for `Hat`: if the map is C^2(S^1) and expanding, then the branches of `g` are either all increasing or all decreasing. But it is an additional assumption that we'd need to make.)
